### PR TITLE
Fix/d2p compat mk2

### PR DESCRIPTION
**Pull request by SysPete**
PR adds 2 commits to existing https://github.com/jbarrett/Dancer2-Plugin-UnicodeNormalize/pull/5

I hate version-specific conditionals but perhaps this could be considered as a short-term measure so that this plugin can be released before Plugin2 is merged?

@xsawyerx: I pulled a method at random out of the bag for the conditional check. Do you have a preferred check to my `can`?

### CODE REVIEW

**Comment by jbarrett** [comment]
Thanks @SysPete! LGTM :+1: - I think the overhead of this check pales in comparison to the plugin's primary function...

Will hang on a short while for @xsawyerx's input before release.

**Comment by xsawyerx** [comment]
I'll take a look at this tomorrow. It's kind of late and my mind isn't working really well.

**Comment by SysPete** [comment]
@xsawyerx are you still planning to look at this one? I'd like to ask @jbarrett to cook up a new release for CPAN if you're happy.

**Comment by jbarrett** [comment]
@SysPete @xsawyerx Really sorry about the delay on releasing this!

This currently does not apply normalisation to the new Hash::MultiValue *_parameters accessors, so I tried and failed to fix this (I think I blocked on body_parameters which basically forwards what Plack::Request hands over... I remember thinking "Hmmm, this should probably be Plack Middleware really").

**Pull request merged**
